### PR TITLE
Update vote.ts as per new proposal.

### PR DESCRIPTION
**Pull request by Vulpicula**
Don't add this until the proposal actually passes.

### CODE REVIEW

**Comment by CaptainObi** [comment]
uhh @Vulpicula the last 2 commits should be their own pr, just in case the vote no pass. but ig its fine

**Comment by Vulpicula** [comment]
Fair, aye. I'll split them off if the proposal doesn't pass. The code looks fine, aye?

**Comment by CaptainObi** [comment]
aye, bit sad to see the error message go :(

**Comment by Vulpicula** [comment]
I liked it too, but I think it's best if the error message is actually useful rather than confusing. We can always add more easter eggs, though. :p

**Comment by Vulpicula** [comment]
Wonder if I can rename the branch.

**Review by Dinty1 — APPROVED** [review]

**Pull request merged**
